In [1]:
import numpy as np
from itertools import combinations_with_replacement
from itertools import product

In [2]:
#Assumes a design matrix with n factors; orthogonal design of 2 factors per level plus a midpoint (-1, 0, 1)

# ***TO DO***
# 1. Add categorical variable functionality
# 2. Add more flexibility for greater than 3 design points? 

def initial_matrix(num_factors):
    
    #Itertools product gets every combination of -1, 0, 1 for the number of factors the the experiment
    #Then cast to a numpy array
    
    return np.array(list(product(['-1', '0', '1'], repeat = num_factors)), dtype = 'float64')

In [3]:
a = initial_matrix(3)
a

array([[-1., -1., -1.],
       [-1., -1.,  0.],
       [-1., -1.,  1.],
       [-1.,  0., -1.],
       [-1.,  0.,  0.],
       [-1.,  0.,  1.],
       [-1.,  1., -1.],
       [-1.,  1.,  0.],
       [-1.,  1.,  1.],
       [ 0., -1., -1.],
       [ 0., -1.,  0.],
       [ 0., -1.,  1.],
       [ 0.,  0., -1.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1., -1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  1.],
       [ 1., -1., -1.],
       [ 1., -1.,  0.],
       [ 1., -1.,  1.],
       [ 1.,  0., -1.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  1.],
       [ 1.,  1., -1.],
       [ 1.,  1.,  0.],
       [ 1.,  1.,  1.]])

In [4]:
#Add the desired interaction effects. Interactions is a list of tuples with desired variable inteactions

# ***TO DO***
# 1. Add a case for no interactions

def interactions(design_matrix, interactions):
    
    #Use if all interaction effects are desired
    if interactions == 'FULL':
        
        #Gets all possible 2 way interactions
        effects = list(combinations_with_replacement(range(design_matrix.shape[1]), 2))
        
        #Loop through each set of interactions effects
        for ind in effects:
            
            #Compute the interaction then make a column vector 
            interaction_col = np.array(design_matrix[:, ind[0]] * design_matrix[:, ind[1]]).reshape(design_matrix.shape[0], 1)
            
            #Add to the end of the design matrix as a new column
            design_matrix = np.hstack((design_matrix, interaction_col))
            
    else:
        #Same procedure as above but with user specified interactions
        for ind in interactions:
            interaction_col = np.array(design_matrix[:, ind[0]] * design_matrix[:, ind[1]]).reshape(design_matrix.shape[0], 1)
            design_matrix = np.hstack((design_matrix, interaction_col))
     
    #Add intercept to the design matrix
    design_matrix = np.hstack((design_matrix, np.ones((design_matrix.shape[0], 1))))
  
    return design_matrix
            

In [5]:
interactions(a, 'FULL')

array([[-1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [-1., -1.,  0.,  1.,  1., -0.,  1., -0.,  0.,  1.],
       [-1., -1.,  1.,  1.,  1., -1.,  1., -1.,  1.,  1.],
       [-1.,  0., -1.,  1., -0.,  1.,  0., -0.,  1.,  1.],
       [-1.,  0.,  0.,  1., -0., -0.,  0.,  0.,  0.,  1.],
       [-1.,  0.,  1.,  1., -0., -1.,  0.,  0.,  1.,  1.],
       [-1.,  1., -1.,  1., -1.,  1.,  1., -1.,  1.,  1.],
       [-1.,  1.,  0.,  1., -1., -0.,  1.,  0.,  0.,  1.],
       [-1.,  1.,  1.,  1., -1., -1.,  1.,  1.,  1.,  1.],
       [ 0., -1., -1.,  0., -0., -0.,  1.,  1.,  1.,  1.],
       [ 0., -1.,  0.,  0., -0.,  0.,  1., -0.,  0.,  1.],
       [ 0., -1.,  1.,  0., -0.,  0.,  1., -1.,  1.,  1.],
       [ 0.,  0., -1.,  0.,  0., -0.,  0., -0.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
       [ 0.,  1., -1.,  0.,  0., -0.,  1., -1.,  1.,  1.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.

In [6]:
interactions(a, [(1, 2)])

array([[-1., -1., -1.,  1.,  1.],
       [-1., -1.,  0., -0.,  1.],
       [-1., -1.,  1., -1.,  1.],
       [-1.,  0., -1., -0.,  1.],
       [-1.,  0.,  0.,  0.,  1.],
       [-1.,  0.,  1.,  0.,  1.],
       [-1.,  1., -1., -1.,  1.],
       [-1.,  1.,  0.,  0.,  1.],
       [-1.,  1.,  1.,  1.,  1.],
       [ 0., -1., -1.,  1.,  1.],
       [ 0., -1.,  0., -0.,  1.],
       [ 0., -1.,  1., -1.,  1.],
       [ 0.,  0., -1., -0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  0.,  1.],
       [ 0.,  1., -1., -1.,  1.],
       [ 0.,  1.,  0.,  0.,  1.],
       [ 0.,  1.,  1.,  1.,  1.],
       [ 1., -1., -1.,  1.,  1.],
       [ 1., -1.,  0., -0.,  1.],
       [ 1., -1.,  1., -1.,  1.],
       [ 1.,  0., -1., -0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.],
       [ 1.,  1., -1., -1.,  1.],
       [ 1.,  1.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])